"""Add version and lock fields to user table

Revision ID: b2bc0cb6b1e7
Revises: c88bd9002b97
Create Date: 2026-03-24 22:58:13.035447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2bc0cb6b1e7'
down_revision: Union[str, Sequence[str], None] = 'c88bd9002b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('version', sa.Integer(), nullable=True, comment='Version of the user record (for optimistic locking)'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE users SET version = 1, failed_login_attempts = 0")

    op.alter_column('users', 'version', nullable=False)
    op.alter_column('users', 'failed_login_attempts', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'version')
    # ### end Alembic commands ###
